language: node_js

os:
  - linux

before_script:
  - npm install -g gatsby

node_js:
  - "12.13"

deploy:
  provider: script
  script: cd docs/ && yarn install && yarn run deploy
  cleanup: true
  on:
    branch: master
