language: c
os: linux

jobs:
  include:
    - stage: deployment
      name: "Deploy GitHub Pages Documentation"
      language: node_js
      node_js:
        - 12
      before_script:
        - cd docs/
        - yarn install
      script:
        - yarn run deploy
      deploy:
        provider: pages
        cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs/public
        on:
          branch: master
