language: c
os: linux

jobs:
  include:
    - stage: deployment
      name: "Deploy GitHub Pages Documentation"
      node_js: "12.13"
      before_script:
        - npm install -g gatsby
      script:
        - cd docs/
        - yarn install
        - yarn run deploy
      deploy:
        provider: script
        cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
