language: c
os: linux

jobs:
  include:
    - stage: build
      name: "Compile source with build tools"
      services:
        - docker
      before_install:
        - docker pull espressif/idf
      install:
        - git clone https://github.com/Kanaderu/esp-idf-lib
      script:
        - docker run --rm \
          -it \
          #--privileged \
          #--device /dev/ttyUSB0:/dev/ttyUSB0 \
          #--user $(id -u):$(id -g) \
          -e IDF_LIB_PATH=/esp-lib \
          -e LC_ALL=C.UTF-8 \
          -v $PWD/esp-idf-lib:/esp-lib \
          -v $PWD:/project \
          -w /project \
          espressif/idf idf.py -p /dev/ttyUSB0 build

    - stage: deployment
      name: "Deploy GitHub Pages Documentation"
      language: node_js
      node_js:
        - 12
      before_script:
        - cd docs/
        - yarn install
      script:
        - yarn run deploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs/public
        on:
          branch: master
